config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
     resource :relationships, only: [:create, :destroy]
     get :follows, on: :member
     get :followers, on: :member
  end
  root to: "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  
  validates :username, presence: true, length: { maximum: 20}

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def after_update_path_for(resource)
    user_path(current_user)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isroom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:id).permit(:username, :avatar, :explanations, :twitter, :facebook, :instagram)
  end
    
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<div class="main users-index">
  <div class="container">
      <% @users.each do |user| %>
      <div class="profile border border-gray pt-3">
        <% if user.avatar? %>
          <img src='<%= user.avatar.url %>', class="icon" alt="ユーザーアイコン">
        <% else %>
          <img src="/assets/default.png", class="icon" alt="ユーザーアイコン">
        <% end %>
        <div class="users-index-item">
          <%= link_to user.username, user_path(user.id), class: "link font-weight-bold text-purple index-name" %><br>
          <%= truncate(user.explanations, length: 80) %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="main users-index">
  <div class="container">
      <% @users.each do |user| %>
      <div class="profile border border-gray pt-3">
        <% if user.avatar? %>
          <img src='<%= user.avatar.url %>', class="icon" alt="ユーザーアイコン">
        <% else %>
          <img src="/assets/default.png", class="icon" alt="ユーザーアイコン">
        <% end %>
        <div class="users-index-item">
          <%= link_to user.username, user_path(user.id), class: "link font-weight-bold purple index-name" %><br>
          <%= truncate(user.explanations, length: 80) %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
      <% @users.each do |user| %>
      <div class="profile border border-gray pt-3">
        <% if user.avatar? %>
          <img src='<%= user.avatar.url %>', class="icon" alt="ユーザーアイコン">
        <% else %>
          <img src="/assets/default.png", class="icon" alt="ユーザーアイコン">
        <% end %>
        <div class="users-index-item">
          <%= link_to user.username, user_path(user.id), class: "link font-weight-bold index-name text-primary" %><br>
          <div class= "index-explanations">
              <%= truncate(user.explanations, length: 80) %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="show-main">
    <div class="show-profile">
      <% if @user.avatar? %>
          <img src='<%= @user.avatar.url %>', class="show-icon" alt="ユーザーアイコン">
      <% else %>
          <img src="/assets/default.png" class="show-icon" alt="ユーザーアイコン" %>
      <% end %>
      <div class="user-show font-weight-bold">
          <%= @user.username %>
          <ul class="profile-links">
          <% if @user.twitter.present? %>
            <li class="profile-link">
              <%= link_to @user.twitter, target: :_blank do %>
                <i class="fab fa-twitter"></i>
              <% end %>
            </li>
          <% end %>
          <% if @user.facebook.present? %>
              <li class="profile-link">
                <%= link_to @user.facebook, target: :_blank do %>
                  <i class="fab fa-facebook"></i>
                <% end %>
              </li>
            <% end %>
            <% if @user.instagram.present? %>
              <li class="profile-link">
                <%= link_to @user.instagram, target: :_blank do %>
                  <i class="fab fa-instagram"></i>
                <% end %>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
    <% if current_user.id == @user.id %>
      <%= link_to "プロフィールを書く", edit_user_registration_path, class: "link profile-edit text-secondary float-right" %><br>
    <% end %>
    <div class="container-fluid">
      <%=link_to "#{@user.followings.count}フォロー中", follows_user_path(@user.id), class: "follow text-dark" %>
      <%=link_to "#{@user.followers.count}フォロワー", followers_user_path(@user.id), class: "follow text-dark" %>
      <% if current_user != @user %>
        <% if @user.followed_by?(current_user) %>
            <%=link_to "フォロー済み", user_relationships_path(@user.id), method: :delete, class: "follow-button" %>
        <% else %>
            <%=link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "follow-button" %>
        <% end %>
      <% end %>
    <% unless @user.id == current_user.id %>
      <% if (current_user.followed_by? @user) && (@user.followed_by? current_user) %>
      <% if @isRoom == true %>
        <p class= "user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: @user.id %>
          <% end %>
          <%= f.submit "チャットを始める", class: "btn btn-primary btn-lg user-show-chat" %>
        <% end %>  
     <% end %>
     <% end %>
    <% end %>
      <div class= "explanations">
        <div class="career">経歴</div>
        <div class="career-intro">
            <%= simple_format(h(@user.explanations)) %>
        </div>
      </div>
    </div>
  </div>
</div>